<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>El Traductor 3000</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.css" />
    <link rel="stylesheet" href="https://bulma.io/vendor/fontawesome-free-5.15.2-web/css/all.min.css" />
    <link rel="stylesheet" href="./style.css" />
</head>

<body>
    <main>
        <div class="columns is-centered">
            <div class="column is-4">
                <h1 class="title is-1 is-centered">ez File uploader 3000</h1>
                <h3 class="subtitle is-3 is-centered">.gif / .png / .jpeg / .jpg</h3>
                <form method="post" class="box" enctype="multipart/form-data" action="index.php">
                    <div id="file-js-example" class="file has-name">
                        <label class="file-label">
                            <input class="file-input" type="file" name="file">
                            <span class="file-cta">
                                <span class="file-icon">
                                    <i class="fas fa-upload"></i>
                                </span>
                                <span class="file-label">
                                    Choose a file…
                                </span>
                            </span>
                            <span class="file-name">
                                No file uploaded
                            </span>
                        </label>

                    </div>
                    <div class="control">
                        <button class="button is-primary">Submit</button>
                    </div>
                    <script>
                        const fileInput = document.querySelector('#file-js-example input[type=file]');
                        fileInput.onchange = () => {
                            if (fileInput.files.length > 0) {
                                const fileName = document.querySelector('#file-js-example .file-name');
                                fileName.textContent = fileInput.files[0].name;
                            }
                        }
                    </script>
            </div>
            </form>
        </div>
        <div class="column">

        </div>
        </div>
    </main>
</body>

</html>