<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./table.css">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.0/css/bulma.css" />
</head>

<body>
    <?php require 'table.php'; ?>
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
        <ul class="pagination-list">
            <?php for ($i = 1; $i <= ceil($numberOfEmployees['COUNT(*)'] / $base); $i++) : ?>
                <?php if($index == $i): ?>
                    <li>
                        <a class="pagination-link is-current" aria-label=<?= "Page ".$i ?> aria-current="page"><?= $i ?></a>
                    </li>
                <?php else : ?>
                    <li>
                        <a href=<?= "./index.php?index=".$i ?> class="pagination-link" aria-label=<?= "Page ".$i ?>><?= $i ?></a>
                    </li>
                <?php endif ?>
            <?php endfor ?>
        </ul>
    </nav>
</body>

</html>